name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          FOLDER_NAME=basics
          echo "# $FOLDER_NAME" > README.md
          echo "" >> README.md
          for file in $(ls $FOLDER_NAME); do
            echo "- [$file]($FOLDER_NAME/$file)" >> README.md
          done

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with list of files in $FOLDER_NAME"
          git push
